name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./seatselection/pom.xml
          mvn clean package -f ./seat/pom.xml
          mvn clean package -f ./reservation/pom.xml
          mvn clean package -f ./customercenter/pom.xml

      - name: Docker Build and push for Seatselection
        uses: docker/build-push-action@v4
        with:
          context: ./seatselection
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/seatselection:latest
            ghcr.io/${{ github.repository }}/seatselection:${{ github.ref_name }}
            
      - name: Docker Build and push for Seat
        uses: docker/build-push-action@v4
        with:
          context: ./seat
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/seat:latest
            ghcr.io/${{ github.repository }}/seat:${{ github.ref_name }}
            
      - name: Docker Build and push for Reservation
        uses: docker/build-push-action@v4
        with:
          context: ./reservation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservation:latest
            ghcr.io/${{ github.repository }}/reservation:${{ github.ref_name }}
            
      - name: Docker Build and push for Customercenter
        uses: docker/build-push-action@v4
        with:
          context: ./customercenter
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customercenter:latest
            ghcr.io/${{ github.repository }}/customercenter:${{ github.ref_name }}
            
