---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatselection
  labels:
    app: seatselection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seatselection
  template:
    metadata:
      labels:
        app: seatselection
    spec:
      containers:
        - name: seatselection
          image: username/seatselection:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat
  labels:
    app: seat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat
  template:
    metadata:
      labels:
        app: seat
    spec:
      containers:
        - name: seat
          image: username/seat:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: username/reservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customercenter
  labels:
    app: customercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customercenter
  template:
    metadata:
      labels:
        app: customercenter
    spec:
      containers:
        - name: customercenter
          image: username/customercenter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: seatselection
  labels:
    app: seatselection
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: seatselection


---


apiVersion: v1
kind: Service
metadata:
  name: seat
  labels:
    app: seat
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: seat


---


apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservation


---


apiVersion: v1
kind: Service
metadata:
  name: customercenter
  labels:
    app: customercenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customercenter

