apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatselection
  labels:
    app: seatselection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seatselection
  template:
    metadata:
      labels:
        app: seatselection
    spec:
      containers:
        - name: seatselection
          image: "username/seatselection:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
